service: api-metro-dev-location-tracking-service

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  timeout: 30
  memorySize: 512
  environment:
    MONGODB_URI: ${ssm:/metro/${self:provider.stage}/mongodb/uri}
    MONGODB_DB: ${ssm:/metro/${self:provider.stage}/mongodb/db}
    JWT_SECRET: ${ssm:/metro/${self:provider.stage}/jwt/secret}
    NODE_ENV: ${self:provider.stage}

functions:
  api:
    handler: lambda.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

custom:
  serverless-offline:
    httpPort: 3000
    lambdaPort: 3002